---
title: "Tables with datagrid()"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{datagridr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(toastui)
```


## Usage

Create a table:

```{r}
datagrid(rolling_stones_50)
```

```{r}
datagrid(rolling_stones_50, colwidths = NULL) %>% 
  grid_columns(whiteSpace = "pre-line")
```


```{r}
datagrid(rolling_stones_50) %>% 
  grid_columns(resizable = TRUE)
```


```{r}
datagrid(rolling_stones_50) %>% 
  grid_columns(vars = c("Number", "Year"), width = 150)
```



## Sort

Sort is activated by default, you can desactivate like this:

```{r}
datagrid(rolling_stones_50, sortable = FALSE)
```



## Filter

You can allow filtering rows in the table with:

```{r}
datagrid(rolling_stones_50, filters = TRUE)
```


You can customize filter type with `grid_filters()`:

```{r}
datagrid(rolling_stones_50) %>% 
  grid_filters(
    vars = "Artist", 
    showApplyBtn = TRUE, 
    showClearBtn = TRUE, 
    type = "text"
  )
```


## Pagination

Activat pagination by indicating the number of rows to display:

```{r}
datagrid(rolling_stones_50, pagination = 8)
```



## Group columns

Group columns under a common label:

```{r}
datagrid(head(iris)) %>%
  grid_complex_header(
    "Sepal" = c("Sepal.Length", "Sepal.Width"),
    "Petal" = c("Petal.Length", "Petal.Width")
  )
```



